[package]
name = "agileMate"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "agileMate"
path = "src/main.rs"

[dependencies]
poise = "0.5.5"
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15.0"